#SYST230Project
from cryptography.fernet import Fernet
import os
import os.path
from pathlib import Path
import random
import zipfile
import pyzipper
import pandas as pd

#Fernet: https://www.thepythoncode.com/article/encrypt-decrypt-files-symmetric-python

#In short: 
#a) Fernet generates a key, that key can be used to encrypt and decrypt data. It may look like this
#   "9AFosuDE9Ytk4dPXUDhyPdMhus0_d5knBp585mLlGs4=""
#b) Next, a blank dictionary should be made and saved to a file called "Vault.txt". Here is where passwords will be stored. in a format like 
#	{"Netflix":"P@55w0rd!", "Amazon":"Password123!"}
#c) The key will be used to encrypt and decrypt the data in Vault.
#d) When not in use, the key should be zipped with a password (the master password). This will only be unzipped to decrypt or encrypt "Vault.txt"

#TODO: UI, Delete a password, check to make sure passwords generated are unique within the Vault, add a check to make sure that the initial startup has been completed
#autolock after a change, 


def generatePassword(): #generates a random 12 character password. For later use
	possible_characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&()*+,-./:;<=>?@[\]^`{|}~'
	newpass = ""
	for i in range(0,12):
		random_number = random.randint(0, len(possible_characters))
		newpass = newpass + possible_characters[random.randint(0, len(possible_characters))]
	return(newpass)

def write_key():#this generates a key for the master password. This should ONLY be used when the program is first used
	key = Fernet.generate_key()
	with open("key.key", "wb") as key_file:
		key_file.write(key)

def load_key():#after the key is created, this function is used to access it in order to secure information. (loads the file key.key)
	return open("key.key", "rb").read()

def zip_and_delete(inputfile, password): #used to zip a file and delete the non password protected one
	secret_password = password
	with pyzipper.AESZipFile(inputfile+'.zip','w',compression=pyzipper.ZIP_LZMA,encryption=pyzipper.WZ_AES) as zf:
		zf.setpassword(secret_password)
		with open(inputfile, 'r') as file:
			data = file.read()
			zf.writestr(inputfile, data)
	with pyzipper.AESZipFile(inputfile+'.zip') as zf:
		zf.setpassword(secret_password)
		my_secrets = zf.read(inputfile)
	os.remove(inputfile)

def zipWithUserPass(): #this zips the key.key file (generated by "testFernet()") with the inputted password.
	path_to_file = 'key.key'
	path = Path(path_to_file)
	if path.is_file(): #if key.key exists, then
		print(f'The file {path_to_file} exists')
		password = ""
		check1 = ""
		check2 = ""
		inputpass = True
		while inputpass == True:
			check1 = input("Input Password: ")
			check2 = input("Input Password Again: ")
			if check1 == check2:
				password = check1
				inputpass = False
			else:
				print("Passwords do not match. Try again.")
		zip_and_delete(path_to_file, bytes(password, 'utf-8'))#passes to zip and delete
	else:
		print(f'The file {path_to_file} does not exist')

def getFernetKey(prompt): #gets firnet key from the zip file without unzipping it
	inputpass = input(prompt+": ")
	try:
		with pyzipper.AESZipFile('key.key.zip') as f:
			f.pwd = bytes(inputpass, 'utf-8')
			file_content = f.read('key.key')
			key_in_mem = (file_content)
			return key_in_mem #returns the key and stores it in memory for use
	except PasswordError: #should add something to make sure people dont try to brute force
		print("password was entered incorrectly")

def createPasswordTable():
	table = [["DefaultApp","Password"]]
	pd.DataFrame(table).to_csv("Vault.csv",index=False)
	encrypt("Vault.csv", getFernetKey("Confirm Password")) #encrypt the Vault

def addToPasswordTable(key):
	decrypt("Vault.csv", key)#decrypt Vault
	df = pd.read_csv (r"Vault.csv")
	table = df.values.tolist()
	newCompany = input("Password Name: ")
	newPass = generatePassword()
	table.append([newCompany,newPass])
	pd.DataFrame(table).to_csv("Vault.csv",index=False)
	encrypt("Vault.csv", getFernetKey("Input Password to Save Changes"))#then encrypt it again

def viewPasswordTable(key):
	decrypt("Vault.csv", key)#decrypt Vault
	df = pd.read_csv (r"Vault.csv")
	table = df.values.tolist()
	print(table)
	encrypt("Vault.csv", key)#encrypt vault

def encrypt(filename, key): #function used to encrypt Vault.exe
	f = Fernet(key)
	with open(filename, "rb") as file:
		# read all file data
		file_data = file.read()
	# encrypt data
	encrypted_data = f.encrypt(file_data)
	# write the encrypted file
	with open(filename, "wb") as file:
		file.write(encrypted_data)

def decrypt(filename, key): #function used to decrypt Vault.exe
	f = Fernet(key)
	with open(filename, "rb") as file:
		# read the encrypted data
		encrypted_data = file.read()
	# decrypt data
	decrypted_data = f.decrypt(encrypted_data)
	# write the original file
	with open(filename, "wb") as file:
		file.write(decrypted_data)

def initialSetup():
	write_key() #creates master AES key for your system
	zipWithUserPass() #secure the key with master password
	createPasswordTable() #sets up vault.csv with default company and password
	#lock the table here


def returning(key):
	#unlock password table here with the function getFernetKey()
	#ask to add or view it
	print("Hello Returning User!\n")
	ask = True
	while ask == True:
		options = input("Would you like to\n1)View Passwords\n2)Generate New Password\n3)Exit")
		if "1" in options:
			viewPasswordTable(key) #view the table of passwords
		if "2" in options:
			addToPasswordTable(key) #add to the table of passwords
		if "3" in options:
			ask = False
			print("Goodbye!")

def testFernet():
	#generate and write a new key
	write_key() 
	# load the previously generated key
	key = load_key()
	print("compare the zip to this!\n")
	print(key)
	#encode with the generated key:
	print("Encoding the message 'some secret message'")
	message = "some secret message".encode()
	# initialize the Fernet class
	f = Fernet(key)
	# encrypt the message
	encrypted = f.encrypt(message)
	# print how it looks
	print(encrypted)
	print("DECRYPTING")
	decrypted_encrypted = f.decrypt(encrypted)
	print(decrypted_encrypted)


def run():
	if ("key.key.zip" in os.listdir()) and ("Vault.csv" in os.listdir()):
		key = getFernetKey("Input Password to Log In")
		returning(key)#this should only be run after the first startup has been creates sucessfully
	else:
		print("Lets set up your password manager!\n")
		initialSetup()#this should only be run on first startup
		print("Thanks for setting everything up!\nPlease run the program again to access its features")

run()


